// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (
    code,
    name
)
VALUES ($1, $2)
RETURNING
    id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
`

type CreateBrandParams struct {
	Code string
	Name string
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, arg.Code, arg.Name)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :execresult
UPDATE brands
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteBrand(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteBrand, id)
}

const getBrandByCode = `-- name: GetBrandByCode :one
SELECT
    id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM brands
WHERE code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetBrandByCode(ctx context.Context, code string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByCode, code)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT
    id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM brands
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, code, name, created_at, updated_at, deleted_at
FROM brands
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands
SET
    code = $2,
    name = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
`

type UpdateBrandParams struct {
	ID   uuid.UUID
	Code string
	Name string
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.ID, arg.Code, arg.Name)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
