// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    parent_id,
    code,
    name
)
VALUES ($1, $2, $3)
RETURNING
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
`

type CreateCategoryParams struct {
	ParentID *uuid.UUID
	Code     string
	Name     string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ParentID, arg.Code, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
UPDATE categories
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCategory, id)
}

const getCategoryByCode = `-- name: GetCategoryByCode :one
SELECT
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM categories
WHERE code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByCode(ctx context.Context, code string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByCode, code)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM categories
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM categories
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM categories
WHERE parent_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListChildCategories(ctx context.Context, parentID *uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listChildCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
FROM categories
WHERE parent_id IS NULL
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    parent_id = $2,
    code = $3,
    name = $4,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    parent_id,
    code,
    name,
    created_at,
    updated_at,
    deleted_at
`

type UpdateCategoryParams struct {
	ID       uuid.UUID
	ParentID *uuid.UUID
	Code     string
	Name     string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.ParentID,
		arg.Code,
		arg.Name,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
