// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (
    code,
    description
)
VALUES (
    $1,
    $2
)
RETURNING id, code, description, created_at, updated_at
`

type CreatePermissionParams struct {
	Code        string
	Description pgtype.Text
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Code, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
