// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
`

type CreateProductParams struct {
	Sku         string
	Name        string
	CategoryID  uuid.UUID
	BrandID     *uuid.UUID
	UnitID      uuid.UUID
	MinStock    int32
	Weight      pgtype.Numeric
	Length      pgtype.Numeric
	Width       pgtype.Numeric
	Description pgtype.Text
	Status      string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.BrandID,
		arg.UnitID,
		arg.MinStock,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Description,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BrandID,
		&i.UnitID,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM products
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BrandID,
		&i.UnitID,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM products
WHERE sku = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BrandID,
		&i.UnitID,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM products
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.BrandID,
			&i.UnitID,
			&i.MinStock,
			&i.Weight,
			&i.Length,
			&i.Width,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByBrand = `-- name: ListProductsByBrand :many
SELECT
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM products
WHERE brand_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProductsByBrand(ctx context.Context, brandID *uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.BrandID,
			&i.UnitID,
			&i.MinStock,
			&i.Weight,
			&i.Length,
			&i.Width,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM products
WHERE category_id = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.BrandID,
			&i.UnitID,
			&i.MinStock,
			&i.Weight,
			&i.Length,
			&i.Width,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByStatus = `-- name: ListProductsByStatus :many
SELECT
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM products
WHERE status = $1
  AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProductsByStatus(ctx context.Context, status string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.BrandID,
			&i.UnitID,
			&i.MinStock,
			&i.Weight,
			&i.Length,
			&i.Width,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    sku = $2,
    name = $3,
    category_id = $4,
    brand_id = $5,
    unit_id = $6,
    min_stock = $7,
    weight = $8,
    length = $9,
    width = $10,
    description = $11,
    status = $12,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Sku         string
	Name        string
	CategoryID  uuid.UUID
	BrandID     *uuid.UUID
	UnitID      uuid.UUID
	MinStock    int32
	Weight      pgtype.Numeric
	Length      pgtype.Numeric
	Width       pgtype.Numeric
	Description pgtype.Text
	Status      string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.BrandID,
		arg.UnitID,
		arg.MinStock,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Description,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BrandID,
		&i.UnitID,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
