// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
`

type CreateProductParams struct {
	Sku         string
	Name        string
	CategoryID  uuid.UUID
	BrandID     *uuid.UUID
	UnitID      uuid.UUID
	MinStock    int32
	Weight      pgtype.Numeric
	Length      pgtype.Numeric
	Width       pgtype.Numeric
	Description pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.BrandID,
		arg.UnitID,
		arg.MinStock,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BrandID,
		&i.UnitID,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id,
    p.sku,
    p.name,
    c.id AS category_id,
    c.name AS category_name,
    b.id AS brand_id,
    b.name AS brand_name,
    u.id AS unit_id,
    u.name AS unit_name,
    p.min_stock,
    p.weight,
    p.length,
    p.width,
    p.description,
    p.status,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands b     ON b.id = p.brand_id
LEFT JOIN units u      ON u.id = p.unit_id
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID           uuid.UUID
	Sku          string
	Name         string
	CategoryID   *uuid.UUID
	CategoryName pgtype.Text
	BrandID      *uuid.UUID
	BrandName    pgtype.Text
	UnitID       *uuid.UUID
	UnitName     pgtype.Text
	MinStock     int32
	Weight       pgtype.Numeric
	Length       pgtype.Numeric
	Width        pgtype.Numeric
	Description  pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.BrandID,
		&i.BrandName,
		&i.UnitID,
		&i.UnitName,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT
    p.id,
    p.sku,
    p.name,
    c.id AS category_id,
    c.name AS category_name,
    b.id AS brand_id,
    b.name AS brand_name,
    u.id AS unit_id,
    u.name AS unit_name,
    p.min_stock,
    p.weight,
    p.length,
    p.width,
    p.description,
    p.status,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands b     ON b.id = p.brand_id
LEFT JOIN units u      ON u.id = p.unit_id
WHERE p.sku = $1
  AND p.deleted_at IS NULL
`

type GetProductBySKURow struct {
	ID           uuid.UUID
	Sku          string
	Name         string
	CategoryID   *uuid.UUID
	CategoryName pgtype.Text
	BrandID      *uuid.UUID
	BrandName    pgtype.Text
	UnitID       *uuid.UUID
	UnitName     pgtype.Text
	MinStock     int32
	Weight       pgtype.Numeric
	Length       pgtype.Numeric
	Width        pgtype.Numeric
	Description  pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (GetProductBySKURow, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i GetProductBySKURow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.BrandID,
		&i.BrandName,
		&i.UnitID,
		&i.UnitName,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.sku,
    p.name,
    c.id AS category_id,
    c.name AS category_name,
    b.id AS brand_id,
    b.name AS brand_name,
    u.id AS unit_id,
    u.name AS unit_name,
    p.min_stock,
    p.weight,
    p.length,
    p.width,
    p.description,
    p.status,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands b     ON b.id = p.brand_id
LEFT JOIN units u      ON u.id = p.unit_id
WHERE p.deleted_at IS NULL
ORDER BY p.name ASC
`

type ListProductsRow struct {
	ID           uuid.UUID
	Sku          string
	Name         string
	CategoryID   *uuid.UUID
	CategoryName pgtype.Text
	BrandID      *uuid.UUID
	BrandName    pgtype.Text
	UnitID       *uuid.UUID
	UnitName     pgtype.Text
	MinStock     int32
	Weight       pgtype.Numeric
	Length       pgtype.Numeric
	Width        pgtype.Numeric
	Description  pgtype.Text
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.BrandID,
			&i.BrandName,
			&i.UnitID,
			&i.UnitName,
			&i.MinStock,
			&i.Weight,
			&i.Length,
			&i.Width,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    sku = $2,
    name = $3,
    category_id = $4,
    brand_id = $5,
    unit_id = $6,
    min_stock = $7,
    weight = $8,
    length = $9,
    width = $10,
    description = $11,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    sku,
    name,
    category_id,
    brand_id,
    unit_id,
    min_stock,
    weight,
    length,
    width,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Sku         string
	Name        string
	CategoryID  uuid.UUID
	BrandID     *uuid.UUID
	UnitID      uuid.UUID
	MinStock    int32
	Weight      pgtype.Numeric
	Length      pgtype.Numeric
	Width       pgtype.Numeric
	Description pgtype.Text
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.CategoryID,
		arg.BrandID,
		arg.UnitID,
		arg.MinStock,
		arg.Weight,
		arg.Length,
		arg.Width,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.CategoryID,
		&i.BrandID,
		&i.UnitID,
		&i.MinStock,
		&i.Weight,
		&i.Length,
		&i.Width,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
