// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    code,
    name,
    description
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    code,
    name,
    description,
    created_at,
    updated_at
`

type CreateRoleParams struct {
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Code, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO role_permissions (
    role_id,
    permission_id
)
VALUES (
    $1,
    $2
)
`

type CreateRolePermissionParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.Exec(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	return err
}
