// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
    code,
    name
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    code,
    name
`

type CreateUnitParams struct {
	Code string
	Name string
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit, arg.Code, arg.Name)
	var i Unit
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :exec
DELETE FROM units
WHERE id = $1
`

func (q *Queries) DeleteUnit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnit, id)
	return err
}

const getUnitByCode = `-- name: GetUnitByCode :one
SELECT
    id,
    code,
    name
FROM units
WHERE code = $1
`

func (q *Queries) GetUnitByCode(ctx context.Context, code string) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByCode, code)
	var i Unit
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT
    id,
    code,
    name
FROM units
WHERE id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, id uuid.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT
    id,
    code,
    name
FROM units
ORDER BY name ASC
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units
SET
    code = $2,
    name = $3
WHERE id = $1
RETURNING
    id,
    code,
    name
`

type UpdateUnitParams struct {
	ID   uuid.UUID
	Code string
	Name string
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit, arg.ID, arg.Code, arg.Name)
	var i Unit
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}
