// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warehouse.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (
    code,
    name,
    description
) VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    code,
    name,
    description,
    created_at,
    updated_at,
    deleted_at
`

type CreateWarehouseParams struct {
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse, arg.Code, arg.Name, arg.Description)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteWarehouse = `-- name: DeleteWarehouse :execresult
UPDATE warehouses
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteWarehouse, id)
}

const getWarehouseByCode = `-- name: GetWarehouseByCode :one
SELECT
    id,
    code,
    name,
    description,
    created_at,
    updated_at,
    deleted_at
FROM warehouses
WHERE code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetWarehouseByCode(ctx context.Context, code string) (Warehouse, error) {
	row := q.db.QueryRow(ctx, getWarehouseByCode, code)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWarehouseByID = `-- name: GetWarehouseByID :one
SELECT
    id,
    code,
    name,
    description,
    created_at,
    updated_at,
    deleted_at
FROM warehouses
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetWarehouseByID(ctx context.Context, id uuid.UUID) (Warehouse, error) {
	row := q.db.QueryRow(ctx, getWarehouseByID, id)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT
    id,
    code,
    name,
    description,
    created_at,
    updated_at,
    deleted_at
FROM warehouses
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWarehouses(ctx context.Context) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouses
SET
    code = $2,
    name = $3,
    description = $4,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    name,
    description,
    created_at,
    updated_at,
    deleted_at
`

type UpdateWarehouseParams struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, updateWarehouse,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
